#!/bin/bash

echo "cpumanager.sh"
echo "delete.sh"
echo "filemanager.sh"
echo "filepipe.sh"
echo "files.sh"
echo "largestfile.sh"
echo "mem.sh"
echo "mutlipipe.sh"
echo "myCommands.sh"
echo "network.sh"
echo "process.sh"
echo "search.sh"
echo "speak.sh"
echo "startserver.sh"
