commands = {
    "cpumanager": "cpumanager.bat",
    "defender": "defender.bat",
    "delete": "delete.bat",
    "filemanager": "filemanager.bat",
    "filepipe": "filepipe.bat",
    "files": "files.bat",
    "firewall": "firewall.bat",
    "history": "history.bat",
    "largestfile": "largestfile.bat",
    "mem": "mem.bat",
    "multipipe": "multipipe.bat",
    "myCommands":"myCommands",
    "network": "network.bat",
    "process": "process.bat",
    "search": "search.bat",
    "speak": "speak.bat",
    "startserver": "startserver.bat",
    "userAdmin": "userAdmin.bat"
}